name: tp0
services:
  server:
    container_name: server
    image: server:latest
    volumes:
    - ./server/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    networks:
    - testing_net
  client1:
    container_name: client1
    image: client:latest
    volumes:
    - ./client/config.yaml:/config.yaml
    - ./.data/dataset/agency-1.csv:/dataset.csv
    entrypoint: /client
    env_file: ./client/.env
    environment:
    - CLI_ID=1
    networks:
    - testing_net
    depends_on:
    - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
